name: OpenCore
authors: [iTeije]
version: ${project.version}
main: eu.opencore.OpenCore

commands:
  gamemode:
    usage: /<command>
    aliases: gm
  language:
    usage: /<command>
    aliases: lang