name: OpenCore
authors: [iTeije]
version: 0.0.3
api-version: 1.13
main: eu.opencore.OpenCore

commands:
  gamemode:
    usage: /<command>
    aliases: gm
  language:
    usage: /<command>
    aliases: lang
  fly:
    usage: /<command>
  vanish:
    usage: /<command>
    aliases: v